### ISSUE TITLE
求大佬帮忙看看，为什么社区的微调代码刚执行到保存了一个checkpoint就报错

### ISSUE THREAD

**Issue by bapu3212** [LlamaFamily/Llama-Chinese#308]
Traceback (most recent call last):
  File "/root/autodl-tmp/Llama-Chinese/train/sft/finetune_clm_lora.py", line 692, in <module>
    main()
  File "/root/autodl-tmp/Llama-Chinese/train/sft/finetune_clm_lora.py", line 653, in main
    train_result = trainer.train(resume_from_checkpoint=checkpoint)
  File "/root/miniconda3/lib/python3.10/site-packages/transformers/trainer.py", line 1624, in train
    return inner_training_loop(
  File "/root/miniconda3/lib/python3.10/site-packages/transformers/trainer.py", line 2029, in _inner_training_loop
    self._maybe_log_save_evaluate(tr_loss, grad_norm, model, trial, epoch, ignore_keys_for_eval)
  File "/root/miniconda3/lib/python3.10/site-packages/transformers/trainer.py", line 2423, in _maybe_log_save_evaluate
    self._save_checkpoint(model, trial, metrics=metrics)
  File "/root/miniconda3/lib/python3.10/site-packages/transformers/trainer.py", line 2525, in _save_checkpoint
    self.state.save_to_json(os.path.join(staging_output_dir, TRAINER_STATE_NAME))
  File "/root/miniconda3/lib/python3.10/site-packages/transformers/trainer_callback.py", line 113, in save_to_json
    json_string = json.dumps(dataclasses.asdict(self), indent=2, sort_keys=True) + "\n"
  File "/root/miniconda3/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/root/miniconda3/lib/python3.10/json/encoder.py", line 201, in encode
    chunks = list(chunks)
  File "/root/miniconda3/lib/python3.10/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/root/miniconda3/lib/python3.10/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/root/miniconda3/lib/python3.10/json/encoder.py", line 325, in _iterencode_list
    yield from chunks
  File "/root/miniconda3/lib/python3.10/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/root/miniconda3/lib/python3.10/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/root/miniconda3/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Tensor is not JSON serializable

**Comment by t0111** [comment]
https://github.com/LlamaFamily/Llama-Chinese/issues/294#issuecomment-1961686253
