### ISSUE TITLE
执行脚本会出现 json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by dshwei** [LlamaFamily/Llama-Chinese#361]
[2024-09-11 16:33:33,182] [INFO] [comm.py:637:init_distributed] cdb=None
[rank0]: Traceback (most recent call last):
[rank0]:   File "/home/jiuzhan/project/Llama-Chinese/train/sft/finetune_clm_lora.py", line 696, in <module>
[rank0]:     main()
[rank0]:   File "/home/jiuzhan/project/Llama-Chinese/train/sft/finetune_clm_lora.py", line 281, in main
[rank0]:     model_args, data_args, training_args = parser.parse_args_into_dataclasses()
[rank0]:   File "/home/jiuzhan/.conda/envs/llama/lib/python3.10/site-packages/transformers/hf_argparser.py", line 339, in parse_args_into_dataclasses
[rank0]:     obj = dtype(**inputs)
[rank0]:   File "<string>", line 131, in __init__
[rank0]:   File "/home/jiuzhan/.conda/envs/llama/lib/python3.10/site-packages/transformers/training_args.py", line 1976, in __post_init__
[rank0]:     self.hf_deepspeed_config = HfTrainerDeepSpeedConfig(self.deepspeed)
[rank0]:   File "/home/jiuzhan/.conda/envs/llama/lib/python3.10/site-packages/transformers/integrations/deepspeed.py", line 91, in __init__
[rank0]:     super().__init__(config_file_or_dict)
[rank0]:   File "/home/jiuzhan/.conda/envs/llama/lib/python3.10/site-packages/transformers/integrations/deepspeed.py", line 81, in __init__
[rank0]:     super().__init__(config_file_or_dict)
[rank0]:   File "/home/jiuzhan/.conda/envs/llama/lib/python3.10/site-packages/accelerate/utils/deepspeed.py", line 48, in __init__
[rank0]:     config = json.load(f)
[rank0]:   File "/home/jiuzhan/.conda/envs/llama/lib/python3.10/json/__init__.py", line 293, in load
[rank0]:     return loads(fp.read(),
[rank0]:   File "/home/jiuzhan/.conda/envs/llama/lib/python3.10/json/__init__.py", line 346, in loads
[rank0]:     return _default_decoder.decode(s)
[rank0]:   File "/home/jiuzhan/.conda/envs/llama/lib/python3.10/json/decoder.py", line 337, in decode
[rank0]:     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
[rank0]:   File "/home/jiuzhan/.conda/envs/llama/lib/python3.10/json/decoder.py", line 355, in raw_decode
[rank0]:     raise JSONDecodeError("Expecting value", s, err.value) from None
[rank0]: json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[rank1]: Traceback (most recent call last):
[rank1]:   File "/home/jiuzhan/project/Llama-Chinese/train/sft/finetune_clm_lora.py", line 696, in <module>
[rank1]:     main()
[rank1]:   File "/home/jiuzhan/project/Llama-Chinese/train/sft/finetune_clm_lora.py", line 281, in main
[rank1]:     model_args, data_args, training_args = parser.parse_args_into_dataclasses()
[rank1]:   File "/home/jiuzhan/.conda/envs/llama/lib/python3.10/site-packages/transformers/hf_argparser.py", line 339, in parse_args_into_dataclasses
[rank1]:     obj = dtype(**inputs)
[rank1]:   File "<string>", line 131, in __init__
[rank1]:   File "/home/jiuzhan/.conda/envs/llama/lib/python3.10/site-packages/transformers/training_args.py", line 1976, in __post_init__
[rank1]:     self.hf_deepspeed_config = HfTrainerDeepSpeedConfig(self.deepspeed)
[rank1]:   File "/home/jiuzhan/.conda/envs/llama/lib/python3.10/site-packages/transformers/integrations/deepspeed.py", line 91, in __init__
[rank1]:     super().__init__(config_file_or_dict)
[rank1]:   File "/home/jiuzhan/.conda/envs/llama/lib/python3.10/site-packages/transformers/integrations/deepspeed.py", line 81, in __init__
[rank1]:     super().__init__(config_file_or_dict)
[rank1]:   File "/home/jiuzhan/.conda/envs/llama/lib/python3.10/site-packages/accelerate/utils/deepspeed.py", line 48, in __init__
[rank1]:     config = json.load(f)
[rank1]:   File "/home/jiuzhan/.conda/envs/llama/lib/python3.10/json/__init__.py", line 293, in load
[rank1]:     return loads(fp.read(),
[rank1]:   File "/home/jiuzhan/.conda/envs/llama/lib/python3.10/json/__init__.py", line 346, in loads
[rank1]:     return _default_decoder.decode(s)
[rank1]:   File "/home/jiuzhan/.conda/envs/llama/lib/python3.10/json/decoder.py", line 337, in decode
[rank1]:     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
[rank1]:   File "/home/jiuzhan/.conda/envs/llama/lib/python3.10/json/decoder.py", line 355, in raw_decode
[rank1]:     raise JSONDecodeError("Expecting value", s, err.value) from None
[rank1]: json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by dshwei** [comment]
是 deepspeed config的格式问题
